const entities = require("./entities.json");
let text = "";
for (const key of Object.keys(entities)) {
    if (key.startsWith("&") && key.endsWith(";")) {
        if (text) {
            text += ",\n";
        }
        const codePoints = entities[key].codepoints;
        text += `        [${JSON.stringify(key.slice(1, -1))}, [${codePoints.join(", ")}]]`;
    }
}
console.log(`    /*
     * Generated by scripts/buildEntitiesMap.js on for https://html.spec.whatwg.org/entities.json
     */
    const htmlEntities: Map<string, ReadonlyArray<number>> = new Map([\n${text}\n    ]);`);
